pomo:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50  

  lidar_controller:
    type: "effort_controllers/JointPositionController"
    joint: "lidar_joint"
    # TODO : tune pid at some point to match real system, etc.
    pid: {p: 1.0, i: 0.01, d: 0.0}

  velocity_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['left_wheel_joint']
    right_wheel: ['right_wheel_joint']
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    publish_rate: 50
    cmd_vel_timeout: 0.25
    base_frame_id: "base_footprint"
    enable_odom_tf: true
    estimate_velocity_from_position: true 
    
    wheel_radius : 0.18
    wheel_separation : 0.61
    
    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 2.7   # m/s
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.2   # rad/s
