map_type: costmap

obstacle_range: 2.5
raytrace_range: 5.0

#footprint: [[0.2,0.2],[0.2,-0.2],[-0.2,-0.2],[-0.2,0.2]]
footprint: [[0.65,0.4],[-0.42,0.4],[-0.42,-0.4],[0.65,-0.4]]

transform_tolerance: 0.5
first_map_only: false
update_min_a: 0.17

static_layer:
  enabled: True

#obstacle_layer:
#  observation_sources: scan 
#  scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 30.0}
obstacle_layer:
  observation_sources: scan
  scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 30.0, obstacle_range: 5.0, raytrace_range: 10.0}

inflation_layer:
  enabled: True
  inflation_radius: 0.3

grass_layer:
  topic: "/camera/depth_registered/points"
  sensor_frame: "camera_color_optical_frame"
  sensor_timeout: 1.0
  sensor_rate: 30.0
  min_z: -0.1
  max_z: 0.1
  min_h: 60.0
  max_h: 150.0
  min_s: 50.0
  max_s: 180.0
  min_v: 0.0
  max_v: 255.0
  min_range: 0.16
  max_range: 5.0
  clearing: true
  marking: true
  grass_cost: 10.0
  grass_max_cost: 100.0
