global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 4.0
   publish_frequency: 2.0
   width: 40.0
   height: 40.0
   resolution: 0.05
   static_map: true
   rolling_window: false

   plugins:
       - {name: static_layer, type: "costmap_2d::StaticLayer"}
       - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
