wheelchair:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50  
  can_controller:
    type: "pwm_driver/CanController"
    can_port: "vcan0"
    v_scale: 1.27
    w_scale: 1.16
    cmd_timeout: 0.2
    wheel_separation: 0.61
    wheel_radius: 0.1778
    left_wheel: 'left_wheel_joint'
    right_wheel: 'right_wheel_joint'
