topics:
    # data
  - name: /camera/color/camera_info
    timeout: 60.0
    negative: False
  - name: /camera/color/image_raw
    timeout: 60.0
    negative: False
  - name: /camera/depth/camera_info
    timeout: 60.0
    negative: False
  - name: /camera/depth_registered/points
    timeout: 60.0
    negative: False
  - name: /scan
    timeout: 60.0
    negative: False
    # loc / map
  - name: /odom
    timeout: 60.0
    negative: False
  - name: /map
    timeout: 60.0
    negative: False
    # nav
  - name: /cmd_vel
    timeout: 60.0
    negative: False
